# Site settings
title:       Blog
email:       eferdman2@gmail.com
author:      Elizabeth Ferdman
description: "Web Development Blog"
baseurl:     ""
url:         ""

# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true
show_social_icons: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: eferdmangithubio
comments: true

# Social icons
github_username: eferdman
stackoverflow_id: 
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url: 
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Share:'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
highlighter: pygments
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  compressed: true
gems:
  - jekyll-sitemap
